name: Deploy
on:
  push:
    branches: [main]
  
jobs:
  deploy:
    runs-on: ubunbu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: lts/Hydrogen
          
      - name: Cache node modules
        uses: actions/cache@v2.1.8
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jmdb
          
      - name: Pull and restart Docker Container
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            docker pull jwlee134/jmdb
            docker stop jmdb-container
            docker run -d --rm --name jmdb-container -p 80:80 jwlee134/jmdb
          
